gallery pipeline improvements

diff --git a/.github/workflows/actions_s3_update_gallery.yml b/.github/workflows/actions_s3_update_gallery.yml
--- a/.github/workflows/actions_s3_update_gallery.yml
+++ b/.github/workflows/actions_s3_update_gallery.yml
@@ -11,13 +11,16 @@ on:
       - 'actions/**'
 
 jobs:
-  build_and_publish_packages:
+  build_packages:
     runs-on: ubuntu-latest
     permissions:
       id-token: write # required by AWS aws-actions/configure-aws-credentials
       contents: read
     env:
       RCC_VERSION: v18.1.1
+
+    outputs:
+      has_packages: ${{ steps.check_artifacts.outputs.has_packages }}
 
     steps:
       - name: Checkout repository
@@ -39,50 +42,21 @@ jobs:
           chmod +x rcc
           ./rcc run -r publisher/robot.yaml -t "Build updated packages"
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: eu-west-1
-          role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery
-          
-      - name: AWS S3 copies
-        run: |
-          echo "Updating Gallery S3"
-          S3_BASE_URL="s3://downloads.robocorp.com/gallery/actions"
-          cd bin/publisher/gallery
-          ls -la
-
-          # Copy the Action Package subdirectories. Note that since this is an update workflow,
-          # subdirectories will only contain packages which version's was actually bumped.
-          # cache-control max-age=31536000, because these should be immutable.
-          for dir in */; do
-            aws s3 cp "$dir" "$S3_BASE_URL/$dir" --recursive --cache-control max-age=31536000
-            
-              returnCode=$?
-
-              # If the upload of any package fails, we want to break the workflow, as to not update the manifest,
-              # which should be the only source of truth.
-              # Even if some packages will be uploaded before other one fails, manifest won't include them,
-              # and therefore they won't be available in clients to download, and will be eligible to re-upload
-              # on the next Gallery update run.
-              if [ $returnCode -ne 0 ]; then
-                echo "Upload of '$dir' package failed, exiting..."
-                exit 1
-              fi
-          
-          done
-
-          # Copy the updated manifest
-          aws s3 cp manifest.json $S3_BASE_URL/manifest.json --cache-control max-age=120 --content-type "text/plain"
-
       - name: Save Gallery artifact
         uses: actions/upload-artifact@v4
         with:
           name: gallery-artifact
           path: bin/publisher/gallery
 
+      - name: Check artifacts
+        id: check_artifacts
+        run: |
+          if find bin/publisher/gallery -mindepth 1 -maxdepth 1 | read; then
+            echo "has_packages=true" >> $GITHUB_OUTPUT
+          fi
+
   build_environments:
-    needs: build_and_publish_packages
+    needs: build_packages
     runs-on: ${{ matrix.os }}
     env:
       RCC_VERSION: v18.1.1
@@ -103,6 +77,10 @@ jobs:
           - name: macos
             os: macos-latest
             rcc_folder: macos64
+
+    outputs:
+      has_environments: ${{ steps.check_artifacts.outputs.has_environments }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -140,10 +118,20 @@ jobs:
           name: environments-artifact-${{ matrix.os }}
           path: bin/publisher/environments
 
+      - name: Check artifacts
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        id: check_artifacts
+        run: |
+          # Note that it's enough to only do it once (on single OS), running it on all 3 would result
+          # in redundant operations. 
+          if find bin/publisher/environments -mindepth 1 -maxdepth 1 | read; then
+            echo "has_environments=true" >> $GITHUB_OUTPUT
+          fi
 
-  publish_environments:
+
+  publish:
     runs-on: ubuntu-latest
-    needs: build_environments
+    needs: [build_packages, build_environments]
     permissions:
       id-token: write # required by AWS aws-actions/configure-aws-credentials
       contents: read
@@ -152,6 +140,12 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download Gallery artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: gallery-artifact
+          path: bin/publisher/gallery
+
+      - name: Download Environments artifact
         uses: actions/download-artifact@v4
         with:
           pattern: environments-artifact-*
@@ -164,7 +158,8 @@ jobs:
           aws-region: eu-west-1
           role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery
 
-      - name: AWS S3 copies
+      - name: Publish environments
+        if: ${{ needs.build_environments.outputs.has_environments == 'true' }}
         run: |
           S3_BASE_URL="s3://downloads.robocorp.com/holotree/sema4ai"
           cd bin/publisher/environments
@@ -182,3 +177,34 @@ jobs:
               exit 1
             fi
           done
+
+      - name: Publish packages
+        if: ${{ needs.build_packages.outputs.has_packages == 'true' }}
+        run: |
+          echo "Updating Gallery S3"
+          S3_BASE_URL="s3://downloads.robocorp.com/gallery/actions"
+          cd bin/publisher/gallery
+          ls -la
+
+          # Copy the Action Package subdirectories. Note that since this is an update workflow,
+          # subdirectories will only contain packages which version's was actually bumped.
+          # cache-control max-age=31536000, because these should be immutable.
+          for dir in */; do
+            aws s3 cp "$dir" "$S3_BASE_URL/$dir" --recursive --cache-control max-age=31536000
+
+              returnCode=$?
+
+              # If the upload of any package fails, we want to break the workflow, as to not update the manifest,
+              # which should be the only source of truth.
+              # Even if some packages will be uploaded before other one fails, manifest won't include them,
+              # and therefore they won't be available in clients to download, and will be eligible to re-upload
+              # on the next Gallery update run.
+              if [ $returnCode -ne 0 ]; then
+                echo "Upload of '$dir' package failed, exiting..."
+                exit 1
+              fi
+
+          done
+
+          # Copy the updated manifest
+          aws s3 cp manifest.json $S3_BASE_URL/manifest.json --cache-control max-age=120 --content-type "text/plain"
