workflows for prebuilt environments

diff --git a/.github/workflows/actions_s3_init_gallery.yml b/.github/workflows/actions_s3_init_gallery.yml
--- a/.github/workflows/actions_s3_init_gallery.yml
+++ b/.github/workflows/actions_s3_init_gallery.yml
@@ -5,7 +5,7 @@ on:
     # Enables manual triggering via GitHub Actions
 
 jobs:
-  Publish:
+  publish_packages:
     runs-on: ubuntu-latest
     permissions:
       id-token: write # required by AWS aws-actions/configure-aws-credentials
@@ -63,3 +63,71 @@ jobs:
 
           # Copy the updated manifest
           aws s3 cp manifest.json $S3_BASE_URL/manifest.json --cache-control max-age=120 --content-type "text/plain"
+
+      - name: Save Gallery artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: gallery-artifact
+          path: bin/publisher/gallery
+
+  publish_environments:
+    runs-on: ${{ matrix.os }}
+    permissions:
+      id-token: write # required by AWS aws-actions/configure-aws-credentials
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        name:
+          - ubuntu-py3.10
+          - windows-py3.10
+          - macos-py3.10
+        include:
+          - name: ubuntu-py3.10
+            python: '3.10'
+            os: ubuntu-latest
+          - name: windows-py3.10
+            python: '3.10'
+            os: windows-latest
+          - name: macos-py3.10
+            os: macos-latest
+            python: '3.10'
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Download Gallery artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: gallery-artifact
+
+      - name: Build Environments
+        run: |
+          cd bin
+          curl -L -o rcc "https://cdn.sema4.ai/rcc/releases/${{ env.RCC_VERSION }}/linux64/rcc"
+          chmod +x rcc
+          ./rcc run -r publisher/robot.yaml -t "Build environments"
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: eu-west-1
+          role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery
+
+      - name: AWS S3 copies
+        run: |
+          S3_BASE_URL="s3://downloads.robocorp.com/holotree/sema4ai"
+          cd bin/publisher/environments
+          ls -la
+
+          # Copy the environments
+          # cache-control max-age=31536000, because these should be immutable
+          for file in */; do
+            aws s3 cp "$dir" "$S3_BASE_URL/$file" --cache-control max-age=31536000
+
+            returnCode=$?
+
+            if [ $returnCode -ne 0 ]; then
+              echo "Uploading of '$file' environments failed, skipping..."
+            fi
+          done
