exit on environment upload fail, logs reformat

diff --git a/.github/workflows/actions_s3_init_gallery.yml b/.github/workflows/actions_s3_init_gallery.yml
--- a/.github/workflows/actions_s3_init_gallery.yml
+++ b/.github/workflows/actions_s3_init_gallery.yml
@@ -163,6 +163,7 @@ jobs:
             returnCode=$?
 
             if [ $returnCode -ne 0 ]; then
-              echo "Uploading of '$file' environments failed, skipping..."
+              echo "Uploading of '$file' environments failed, exiting..."
+              exit 1
             fi
           done
